# Generated by Django 3.2 on 2021-05-28 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('rut_cliente', models.CharField(max_length=9)),
                ('total', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('GENERADA', 'GENERADA'), ('ANULADA', 'ANULADA')], default='GENERADA', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'boletas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('total', models.PositiveIntegerField()),
                ('boleta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferme.boleta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_cliente', to='ferme.cliente')),
            ],
            options={
                'verbose_name_plural': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=9)),
                ('cargo', models.CharField(choices=[('VENDEDOR', 'VENDEDOR'), ('SUPERVISOR', 'SUPERVISOR'), ('ADMIN', 'ADMIN')], default='VENDEDOR', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('rut_empresa', models.CharField(max_length=9)),
                ('telefono', models.CharField(max_length=9)),
                ('total', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('GENERADA', 'GENERADA'), ('ANULADA', 'ANULADA')], default='GENERADA', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=9)),
                ('rubro', models.CharField(max_length=40)),
                ('empresa', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=400)),
                ('precio', models.PositiveIntegerField()),
                ('stock_actual', models.PositiveIntegerField()),
                ('stock_critico', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('slug', models.SlugField(max_length=80)),
                ('activo', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_categoria', to='ferme.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_marca', to='ferme.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_proveedor', to='ferme.proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_tipo', to='ferme.tipo')),
            ],
            options={
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(default=datetime.datetime.now)),
                ('productos_solicitados', models.TextField(blank=True, max_length=400, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado_orden', models.CharField(choices=[('GENERADA', 'GENERADA'), ('RECIBIDA', 'RECIBIDA'), ('ANULADA', 'ANULADA')], default='GENERADA', max_length=15)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordencompra_empleado', to='ferme.empleado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordencompra_proveedor', to='ferme.proveedor')),
            ],
            options={
                'verbose_name_plural': 'ordenes de compra',
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=9)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('total_devolucion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('GENERADA', 'GENERADA'), ('ANULADA', 'ANULADA')], default='GENERADA', max_length=15)),
                ('boleta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferme.boleta')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notacredito_empleado', to='ferme.empleado')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferme.factura')),
            ],
            options={
                'verbose_name_plural': 'notas de credito',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleorden_ordencompra', to='ferme.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleorden_producto', to='ferme.producto')),
            ],
            options={
                'verbose_name_plural': 'detalle de ordenes',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallecompra_compra', to='ferme.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detallecompra_producto', to='ferme.producto')),
            ],
            options={
                'verbose_name_plural': 'detalle de compras',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_empleado', to='ferme.empleado'),
        ),
        migrations.AddField(
            model_name='compra',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ferme.factura'),
        ),
    ]
