# Generated by Django 3.2 on 2021-05-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalleorden_ordencompra', to='ferme.ordencompra'),
        ),
    ]
