# Generated by Django 3.2 on 2021-06-14 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], default='EFECTIVO', max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='order_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
