# Generated by Django 3.2 on 2021-06-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferme', '0002_auto_20210614_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='medio_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('DEBITO', 'DEBITO'), ('CREDITO', 'CREDITO')], default='EFECTIVO', max_length=200),
        ),
    ]
